packages:
  - 'packages/**'
  - 'examples/**'
  - '!**/test/**'

catalog:
  '@types/react': ^19.0.1
  '@types/react-dom': ^19.0.2
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/react': ^16.1.0
  react: ^19.0.0
  react-dom: ^19.0.0
  tailwindcss: ^3.4.15
  autoprefixer: ^10.4.20
  postcss: ^8.4.49
  vitest: ^2.1.8
  happy-dom: ^15.11.7
