packages:
  - packages/**
  - examples/**
  - '!**/test/**'

catalog:
  '@tailwindcss/vite': ^4.3.3
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.2
  '@types/react': ^19.2.18
  '@types/react-dom': ^19.2.4
  '@vitejs/plugin-react-swc': ^4.3.3
  autoprefixer: ^10.5.4
  happy-dom: ^18.0.1
  postcss: ^8.5.26
  react: ^19.2.8
  react-dom: ^19.2.8
  tailwindcss: 4.3.3
  vite: ^7.3.6
  vitest: ^3.2.7
