packages:
  - packages/**
  - examples/**
  - '!**/test/**'

catalog:
  '@tailwindcss/vite': ^4.1.17
  '@testing-library/jest-dom': ^6.6.4
  '@testing-library/react': ^16.3.0
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react-swc': ^4.2.2
  autoprefixer: ^10.4.21
  happy-dom: ^18.0.1
  postcss: ^8.5.6
  react: ^19.2.1
  react-dom: ^19.2.1
  tailwindcss: 4.1.17
  vite: ^7.2.7
  vitest: ^3.2.4
